- name: "Install zsh on arch"
  ansible.builtin.pacman:
    name:
      - zsh
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Check if zplug is installed arch
  ansible.builtin.stat:
    path: "~/.zplug"
  register: zplug_exists
  when: ansible_distribution == "Archlinux"

- name: Install zplug on arch
  ansible.builtin.shell: "set -o pipefail && curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
  when: ansible_distribution == "Archlinux" and zplug_exists.stat.exists
  changed_when: true

- name: Set default shell
  ansible.builtin.user:
    name: jdr
    shell: /usr/bin/zsh
  when: ansible_distribution == "Archlinux"

- name: "Set default shell arch"
  ansible.builtin.pacman:
    name:
      - zsh
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: "Install zsh packages on osx"
  community.general.homebrew:
    name:
      - zsh-vi-mode
      - zsh-history-substring-search
      - zplug
    state: present
  when: ansible_distribution == "MacOSX"

- name: "Checking for zsh config in dotfiles folder"
  ansible.builtin.stat:
    path: "~/dotfiles/zsh/"
  register: zsh_config

- name: "Stowing zsh config"
  ansible.builtin.shell: "cd ~/dotfiles && stow zsh --verbose=2 --no-folding -R"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  when: zsh_config.stat.exists
