- name: "Install btop on MacOSX"
  community.general.homebrew:
    name: btop
    state: present
  when: ansible_distribution == "MacOSX"

- name: "Install btop on arch"
  ansible.builtin.pacman:
    name:
      - btop
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: "Checking for btop config in dotfiles folder"
  ansible.builtin.stat:
    path: "~/dotfiles/btop/"
  register: btop_config

- name: "Stowing btop config"
  ansible.builtin.shell: "cd ~/dotfiles && stow btop --verbose=2 --no-folding -R"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  when: btop_config.stat.exists
